FROM node:14

# Install global packages
RUN npm install -g gulp-cli mocha

# Copy package.json and package-lock.json into image, then install
# dependencies.
WORKDIR /usr/src/slay
COPY ["package.json", "package-lock.json", "./"]
RUN npm install

# Copy the remaining source files in.
COPY . /usr/src/slay
RUN npm run postinstall
